// Auto-generated by update.js — do not edit manually
// 更新日時: 2026-05-31T09:37:52.246+09:00
const BUDGET_DATA = {
  "generated_at": "2026-05-31T09:37:52.246+09:00",
  "month": "2026-06",
  "data_period": {
    "from": "2026-06-01",
    "to": "2026-06-30"
  },
  "csv_source": "mf_dashboard_input.json (Claude自動取得)",
  "variable_spending": [
    {
      "name": "食費",
      "budget": 35000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "日用品",
      "budget": 10000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "美容",
      "budget": 12000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "被服費",
      "budget": 5000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "交通費",
      "budget": 5000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "趣味・自己投資",
      "budget": 20000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "医療費",
      "budget": 10000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    },
    {
      "name": "婚活費用",
      "budget": 20000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "変動費"
    }
  ],
  "irregular_spending": [
    {
      "name": "ふるさと納税",
      "budget": 0,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "不定期費"
    },
    {
      "name": "家賃更新料",
      "budget": 0,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "不定期費"
    },
    {
      "name": "サーバー代",
      "budget": 0,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "不定期費"
    },
    {
      "name": "転職活動費",
      "budget": 5000,
      "actual": 0,
      "pct": 0,
      "traffic_light": "green",
      "type": "不定期費"
    }
  ],
  "fixed_costs": [
    {
      "name": "家賃",
      "amount": 53000
    },
    {
      "name": "光熱費",
      "amount": 15000
    },
    {
      "name": "通信費",
      "amount": 4913
    },
    {
      "name": "ジム",
      "amount": 11000
    },
    {
      "name": "サブスク",
      "amount": 17488
    }
  ],
  "fixed_total": 101401,
  "variable_budget_total": 117000,
  "variable_actual_total": 0,
  "irregular_budget_total": 5000,
  "irregular_actual_total": 0,
  "grand_budget": 223401,
  "grand_actual": 101401,
  "dividends": {
    "monthly_total": 14423,
    "annual_total": 173072,
    "coverage_pct": 14.2,
    "covers": [
      {
        "name": "通信費",
        "amount": 4913,
        "covered": true,
        "cumulative": 4913
      },
      {
        "name": "ジム",
        "amount": 11000,
        "covered": false,
        "cumulative": 15913
      },
      {
        "name": "光熱費",
        "amount": 15000,
        "covered": false,
        "cumulative": 30913
      },
      {
        "name": "サブスク",
        "amount": 17488,
        "covered": false,
        "cumulative": 48401
      },
      {
        "name": "家賃",
        "amount": 53000,
        "covered": false,
        "cumulative": 101401
      }
    ]
  },
  "investment": {
    "monthly_amount": 10000,
    "income_monthly": 220000,
    "ratio_pct": 4.5,
    "surplus": 108599
  },
  "r_vs_g": {
    "r_pct": 4.55,
    "g_pct": 3,
    "r_gt_g": true,
    "annual_dividend": 173072,
    "principal": 3800000
  },
  "highlights": [
    "r(4.55%) > g(3%) 達成中！資産所得が賃金上昇率を上回っています📈"
  ],
  "improvements": [
    {
      "icon": "💡",
      "text": "投資比率が4.5%です。余力があれば積み立てを増やしましょう（目標：収入の10〜20%）。"
    },
    {
      "icon": "📈",
      "text": "配当で固定費の14.2%をカバー中。高配当株の買い増しでカバー率を上げていきましょう！"
    }
  ],
  "subscriptions_detail": [
    {
      "name": "DMM TV",
      "amount": 550,
      "note": "動画"
    },
    {
      "name": "MindMap",
      "amount": 950,
      "note": "ツール"
    },
    {
      "name": "1password（3年版）",
      "amount": 206,
      "note": "セキュリティ・年払い月換算"
    },
    {
      "name": "adobe XD",
      "amount": 1300,
      "note": "デザイン"
    },
    {
      "name": "リベシティ",
      "amount": 5500,
      "note": "コミュニティ（値上げ反映）"
    },
    {
      "name": "Amazonサプリ",
      "amount": 2830,
      "note": "定期購入"
    },
    {
      "name": "サンドラサプリ",
      "amount": 660,
      "note": "定期購入"
    },
    {
      "name": "マネーフォワードクラウド",
      "amount": 900,
      "note": "家計管理・年払い月換算"
    },
    {
      "name": "xサーバー",
      "amount": 1392,
      "note": "Web・年払い月換算（2027年2月まで）"
    },
    {
      "name": "Claude Pro",
      "amount": 3200,
      "note": "AI・USD$20/月・為替により変動"
    }
  ],
  "subscriptions_source": "budget.json",
  "unmapped_categories": []
};
